name: Build JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Compile Java
        run: javac run.java

      - name: Create Manifest
        run: |
          echo "Main-Class: run" > MANIFEST.MF

      - name: Package JAR
        run: jar cfm run.jar MANIFEST.MF run.class

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-jar
          path: run.jar
