name: Build Stremio Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl build-essential \
            libgtk-3-dev pkg-config libssl-dev libayatana-appindicator3-dev

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Stremio/stremio-service
          path: src

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build release with bundled features
        working-directory: src
        run: |
          cargo build --release --features=bundled

      - name: Build .deb package
        working-directory: src
        run: |
          cargo deb --no-build --features=bundled

      - name: Upload .deb to release
        uses: softprops/action-gh-release@v1
        with:
          name: stremio-service.deb
          files: src/target/debian/*.deb
