name: Build & Release Stremio Service

on:
  push:
    tags:
      - "v*" # Tạo release khi push tag dạng v1.0.0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:11

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git curl build-essential \
            libgtk-3-dev pkg-config libssl-dev libayatana-appindicator3-dev

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Stremio/stremio-service
          path: src

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build release
        working-directory: src
        run: cargo build --release --features=bundled

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Stremio Service ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload binary to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/target/release/stremio-service
          asset_name: stremio-service
          asset_content_type: application/octet-stream
