name: Build Xvfb

on:
  workflow_dispatch:

jobs:
  build-xvfb:
    runs-on: ubuntu-22.04

    steps:
      - name: Install git and tar
        run: |
          sudo apt-get update
          sudo apt-get install -y git tar

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            meson \
            ninja-build \
            pkg-config \
            libx11-dev \
            libxext-dev \
            libxrender-dev \
            libxfont-dev \
            libxau-dev \
            libxdmcp-dev \
            libxcb1-dev \
            libxcb-util-dev \
            libpixman-1-dev \
            xutils-dev \
            libpciaccess-dev \
            zlib1g-dev \
            x11proto-dev \
            x11proto-core-dev \
            x11proto-xext-dev \
            x11proto-fonts-dev \
            libgl1-mesa-dev \
            libdrm-dev \
            libxkbfile-dev \
            libxv-dev

      - name: Download Xorg source
        run: |
          wget https://www.x.org/releases/individual/xserver/xorg-server-21.1.13.tar.xz
          tar -xf xorg-server-21.1.13.tar.xz
          cd xorg-server-21.1.13
          ./configure --prefix=$HOME/.local --enable-xvfb --disable-xorg --disable-xwayland
          make -j$(nproc)
          make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xvfb-binaries
          path: ~/.local/bin/Xvfb
